name: appstest
favicon: null
layout_spectrum: 0.4989
typography_spectrum: 0.25826
title: Appsolute Precision
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff8049'
    - '#0d0c0c'
    - '#602712'
    - '#df441c'
    - '#7f0000'
  brandStrength: 0.75
  lightness: 0.25
  saturation: 0.5625
  rhythmicContrast: 0.6254182131960988
purpose: []
